//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyWorkService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Detail
    {
        public int UserId { get; set; }
        public string Alias { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string MyBackUp { get; set; }
        public double TotalTime { get; set; }
        public string Reason { get; set; }
    }
}
