//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyWorkService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_MSDNUser
    {
        public int Id { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public int IsCheckOut { get; set; }
        public int IsTrainee { get; set; }
        public Nullable<int> TeamId { get; set; }
    }
}
