//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyWorkModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttendanceEntities : DbContext
    {
        public AttendanceEntities()
            : base("name=AttendanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_AdminLog> Tb_AdminLog { get; set; }
        public virtual DbSet<Tb_Detail> Tb_Detail { get; set; }
        public virtual DbSet<Tb_MSDNUser> Tb_MSDNUser { get; set; }
        public virtual DbSet<Tb_Role> Tb_Role { get; set; }
        public virtual DbSet<Tb_TeamInfo> Tb_TeamInfo { get; set; }
        public virtual DbSet<Tb_Technology> Tb_Technology { get; set; }
        public virtual DbSet<Tb_User> Tb_User { get; set; }
    }
}
