//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyWorkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_AdminLog
    {
        public int Id { get; set; }
        public string Alias { get; set; }
        public System.DateTime Time { get; set; }
        public string Remarks { get; set; }
    }
}
