//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace HappyWorkEveryday.RoleServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tb_Role", Namespace="http://schemas.datacontract.org/2004/07/HappyWorkService")]
    public partial class Tb_Role : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string RemarksField;
        
        private int UserLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserLevel {
            get {
                return this.UserLevelField;
            }
            set {
                if ((this.UserLevelField.Equals(value) != true)) {
                    this.UserLevelField = value;
                    this.RaisePropertyChanged("UserLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoleServiceReference.IRoleService")]
    public interface IRoleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Add", ReplyAction="http://tempuri.org/IRoleService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(HappyWorkEveryday.RoleServiceReference.Tb_Role t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Update", ReplyAction="http://tempuri.org/IRoleService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(HappyWorkEveryday.RoleServiceReference.Tb_Role t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Delete", ReplyAction="http://tempuri.org/IRoleService/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(HappyWorkEveryday.RoleServiceReference.Tb_Role t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Find", ReplyAction="http://tempuri.org/IRoleService/FindResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HappyWorkEveryday.RoleServiceReference.Tb_Role))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<HappyWorkEveryday.RoleServiceReference.Tb_Role>))]
        System.Threading.Tasks.Task<HappyWorkEveryday.RoleServiceReference.Tb_Role> FindAsync(object id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/FindAll", ReplyAction="http://tempuri.org/IRoleService/FindAllResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HappyWorkEveryday.RoleServiceReference.Tb_Role>> FindAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoleServiceChannel : HappyWorkEveryday.RoleServiceReference.IRoleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoleServiceClient : System.ServiceModel.ClientBase<HappyWorkEveryday.RoleServiceReference.IRoleService>, HappyWorkEveryday.RoleServiceReference.IRoleService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RoleServiceClient() : 
                base(RoleServiceClient.GetDefaultBinding(), RoleServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRoleService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RoleServiceClient.GetBindingForEndpoint(endpointConfiguration), RoleServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RoleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RoleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(HappyWorkEveryday.RoleServiceReference.Tb_Role t) {
            return base.Channel.AddAsync(t);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(HappyWorkEveryday.RoleServiceReference.Tb_Role t) {
            return base.Channel.UpdateAsync(t);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(HappyWorkEveryday.RoleServiceReference.Tb_Role t) {
            return base.Channel.DeleteAsync(t);
        }
        
        public System.Threading.Tasks.Task<HappyWorkEveryday.RoleServiceReference.Tb_Role> FindAsync(object id) {
            return base.Channel.FindAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HappyWorkEveryday.RoleServiceReference.Tb_Role>> FindAllAsync() {
            return base.Channel.FindAllAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRoleService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRoleService)) {
                return new System.ServiceModel.EndpointAddress("http://10.168.172.218:8090/Services/RoleService/RoleService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return RoleServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRoleService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return RoleServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRoleService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IRoleService,
        }
    }
}
